import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#003B73",
    padding: 16,
    paddingTop: 38,
  },
  Container: {
    flex: 1,
    backgroundColor: "#003B73", // fundo azulfd
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#003B73",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "white",
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  avatarImage: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  header: {
    marginBottom: 20,
    paddingTop: 11,
  },
  timeText: {
    fontSize: 15,
    color: "#666",
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
  IconsContent: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  locationButton: {
    padding: 10,
    backgroundColor: "#f0f6ff",
    borderRadius: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    marginBottom: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    height: 50,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: "#333",
  },
  filterButton: {
    padding: 8,
  },
  filterOptions: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    padding: 16,
    marginHorizontal: 20,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  filterTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
    color: "white",
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#f0f6ff",
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  selectedChip: {
    backgroundColor: "#4A90E2",
  },
  filterChipText: {
    color: "#4A90E2",
    fontSize: 14,
    fontWeight: "500",
  },
  selectedChipText: {
    color: "#fff",
  },
  listContainer: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    marginBottom: 16,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyText: {
    fontSize: 18,
    color: "#666",
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#999",
  },
  centroCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  centroImage: {
    width: "100%",
    height: 160,
  },
  centroContent: {
    padding: 16,
  },
  centroHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  centroName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
    marginRight: 8,
  },
  distanceBadge: {
    backgroundColor: "#4A90E2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  distanceText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  ratingText: {
    marginLeft: 4,
    fontSize: 12,
    color: "#666",
  },
  addressContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  address: {
    marginLeft: 8,
    fontSize: 14,
    color: "#666",
    flex: 1,
  },
  scheduleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  schedule: {
    marginLeft: 8,
    fontSize: 14,
    color: "#666",
    flex: 1,
  },
  activities: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  activityTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#e6f2ff",
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  activityText: {
    fontSize: 12,
    color: "#4A90E2",
    fontWeight: "500",
  },
  moreActivities: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#f0f0f0",
    borderRadius: 16,
  },
  moreActivitiesText: {
    fontSize: 12,
    color: "#666",
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 12,
  },
  smallActionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#f0f6ff",
    borderRadius: 16,
    marginRight: 8,
  },
  smallActionText: {
    marginLeft: 4,
    fontSize: 12,
    color: "#4A90E2",
    fontWeight: "500",
  },
  seeMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    backgroundColor: "#f0f6ff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#4A90E2",
  },
  seeMoreText: {
    color: "#4A90E2",
    fontWeight: "600",
    marginRight: 8,
  },
});
